# Generated by Django 5.0.4 on 2024-04-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwa', '0003_imagevariants_manhwa_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='external_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='external_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
