# Generated by Django 5.0.4 on 2024-04-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwa', '0004_manhwa_external_hash_alter_manhwa_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manhwa',
            old_name='external_hash',
            new_name='hash_external_id',
        ),
        migrations.AddField(
            model_name='manhwa',
            name='hash_slug',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manhwa',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='external_id',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30)),
                ('release_date', models.DateTimeField(null=True)),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manhwa.manhwa')),
            ],
        ),
    ]
