# Generated by Django 5.0.4 on 2024-04-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwa', '0005_rename_external_hash_manhwa_hash_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagevariants',
            name='large',
        ),
    ]
