# Generated by Django 5.0.4 on 2024-04-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manhwa", "0006_remove_imagevariants_large"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indentifier", models.CharField(max_length=64, unique=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="manhwa.chapter",
                    ),
                ),
                (
                    "images",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manhwa.imagevariants",
                    ),
                ),
            ],
        ),
    ]
