# Generated by Django 5.0.4 on 2024-04-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manhwa", "0007_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="images",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manhwa.imagevariants",
            ),
        ),
    ]
