# Generated by Django 5.0.4 on 2024-04-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manhwa", "0008_alter_page_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(max_length=64),
        ),
        migrations.AlterField(
            model_name="imagevariants",
            name="identifier",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="manhwa",
            name="external_id",
            field=models.SlugField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="manhwa",
            name="slug",
            field=models.SlugField(max_length=64, null=True),
        ),
    ]
