# Generated by Django 4.2.9 on 2024-07-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0009_alter_chapter_slug_alter_imagevariants_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagevariants",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="page",
            name="indentifier",
        ),
        migrations.AddField(
            model_name="imagevariants",
            name="translated",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="manhwa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="manhwa.manhwa",
            ),
        ),
    ]
