# Generated by Django 4.2.9 on 2024-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0010_remove_imagevariants_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="identifier",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
