# Generated by Django 4.2.9 on 2024-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0012_alter_chapter_identifier_alter_chapter_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="identifier",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
