# Generated by Django 4.2.9 on 2024-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0013_manhwa_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manhwa",
            name="source",
        ),
        migrations.AddField(
            model_name="manhwa",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
