# Generated by Django 4.2.9 on 2024-07-11 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0014_remove_manhwa_source_manhwa_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manhwa",
            old_name="url",
            new_name="source",
        ),
    ]
