# Generated by Django 4.2.9 on 2024-07-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0015_rename_url_manhwa_source"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Source",
        ),
        migrations.AlterField(
            model_name="manhwa",
            name="source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
