# Generated by Django 4.2.9 on 2025-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0017_chapter_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="quantity_pages",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="quantity_merged",
            field=models.IntegerField(null=True),
        ),
    ]
