# Generated by Django 4.2.9 on 2025-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0018_chapter_quantity_pages_page_quantity_merged"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="is_nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
