# Generated by Django 4.2.9 on 2025-08-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0020_imagevariants_raw_alter_manhwa_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagevariants",
            name="upscaled",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
