# Generated by Django 4.2.9 on 2025-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0022_alter_manhwa_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
