# Generated by Django 4.2.9 on 2026-02-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0023_page_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="page",
            name="translation_cache",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
