# Generated by Django 4.2.9 on 2026-02-19 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0024_alter_page_options_page_translation_cache"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="translation_cache",
        ),
    ]
