# Generated by Django 4.2.9 on 2026-03-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0025_remove_page_translation_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
