# Generated by Django 4.2.9 on 2026-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0029_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="original_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manhwa",
            name="original_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
