# Generated by Django 4.2.9 on 2026-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manhwa", "0030_manhwa_original_description_manhwa_original_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagevariants",
            name="medium",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="imagevariants",
            name="minimum",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="imagevariants",
            name="original",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="imagevariants",
            name="raw",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="imagevariants",
            name="translated",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="imagevariants",
            name="upscaled",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
